---
# setup server

- name: Create new configuration directory structure
  file:
    path: "{{ jboss_eap_home }}/{{ application_id }}/configuration"
    state: directory

- name: Pull configuration file from repo based on app name and version
  get_url:
    url: "{{ repo_url }}/{{ application_id }}/{{ application_version }}/{{ application_configuration }}"
    dest: "{{jboss_eap_home}}/{{ application_id }}/configuration/{{ application_configuration }}"
    validate_certs: False

- name: Load module files into server
  debug:
    msg: "loading modules...."
 
- unarchive:
    src: "{{ repo_url  }}/{{ application_id }}/{{ application_version }}/{{ module_file }}" 
    dest: "{{ jboss_eap_home }}"
    remote_src: True
    validate_certs: False
  when: (load_module is defined or load_module == true) and
        module_file is defined
