# This playbook deploys the whole application stack in this site.
--- 
- name: setup db
  hosts: all
  remote_user: cloud-user
  become: yes

  vars_files:
    - vars/application-config.yml

  roles:
    - common
    - setup_db

- name: configure and deploy the eap applications
  hosts: all
  remote_user: cloud-user
  become: yes
  
  vars_files:
    - vars/application-config.yml

  roles:
    - common    
    - jboss-standalone


